[devPackages]
nodejs = "18"
python = "3.10"

[phases.setup]
nixPkgs = ["python3", "nodejs", "gcc"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[start]
cmd = "python bot.py"
